package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class signupController {
	@FXML
	private PasswordField password;
	@FXML
	private TextField username;
	@FXML
	private TextField name;

	// Event Listener on Button.onAction
	@FXML
	public void userSignup(ActionEvent event) {
		// TODO Autogenerated
	}
}
